/** Export the integral snap-fit coupon exactly as generated by the application. */
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { createServer } from 'vite';
import { build3mf } from '../src/three-mf';
import { renderScadInNode } from '../src/runtime/node-render';
import { inspectPrintableMesh } from '../src/runtime/mesh-check';
import type { ProjectGeometry } from '../src/types';

const vite = await createServer({ configFile: false, logLevel: 'silent', optimizeDeps: { noDiscovery: true, include: [] }, server: { middlewareMode: true, hmr: false, ws: false }, appType: 'custom' });
const { buildTraySnapTest } = await vite.ssrLoadModule('/src/geometry/index.ts') as { buildTraySnapTest(engagement: number): ProjectGeometry };
await vite.close();
for (const engagement of [.1, .2, .3]) {
  const project = buildTraySnapTest(engagement);
  assert.equal(project.parts.length, 2);
  const output = engagement === .2 ? 'artifacts/snap-fit-sample' : `artifacts/snap-fit-sample/engagement-${engagement.toFixed(1)}`;
  await mkdir(output, { recursive: true });
  const meshes = new Map<string, ArrayBuffer>();
  for (const part of project.parts) {
    const { stl } = await renderScadInNode(part.scad);
    assert.ok(stl); inspectPrintableMesh(stl); meshes.set(part.id, stl);
    await writeFile(`${output}/${part.id}.stl`, new Uint8Array(stl));
    await writeFile(`${output}/${part.id}.scad`, part.scad);
  }
  await writeFile(`${output}/snap-fit-test.3mf`, build3mf(project, meshes));
  console.log(`Exported ${engagement.toFixed(1)} mm enclosure snap sample: ${output}`);
}
